<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
    $_helper = $this->helper('Magefan\Blog\Helper\Image');
    $_width = 280;
    $_height = 280;
    $img = $_helper->init($_post->getImage())->resize($_width,$_height);
?>
<div class="em_post-item">
	<div class="post-title">
		<h2><a class="post-item-link" href="<?php echo $_postUrl ?>"><?php echo $_postName; ?></a></h2>
	</div>
	<div class="post-header">
		<div class="post-title-holder clearfix">
            <div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $_postUrl ?>">
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_email"></a>
                <a class="addthis_button_compact"></a>
            </div>
        </div>
        <?php echo $this->getInfoHtml() ?>
	</div>
	<?php if($img): ?>
	<div class="post-image">
		<a href="<?php echo $_postUrl ?>">
		<img class="img-responsive" src="<?php echo $img ?>" alt="<?php echo $_post->getTitle() ?>">
		</a>
	</div>
	<?php endif ?>
	<div class="post-content">
		<div class="post-description clearfix">
            <?php echo $_post->getShortDescription() ?>
            <a class="post-read-more" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>"
               >
               <?php echo __('Read more &#187;') ?>
            </a>
        </div>
	</div>
	<div class="post-footer">

    </div>
</div>
