<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>

<?php
	$_postCollection = $block->getPostCollection();
	$_helper = $this->helper('Magefan\Blog\Helper\Image');
	$_width = 580;
	$_height = 319;
      $classid = md5(json_encode($block->getPostCollection()));
      $_row = 2;
?>
<?php if ($_postCollection->count()) { ?>
<div class="widget block block-static-block">
<div class="row">
<div class="col-sm-24">
<div class="em-line-01">
<!--<div class="em-block-title">
	<h2><span><?php echo __('From Our Blog') ?></span></h2>
</div>-->
<div class="em-slider em-slider-navigation-icon em-slider-from-our-blog em-recent-06" id="<?php echo $classid ?>">
	<?php $i=0;foreach ($_postCollection as $_post) { ?>
	<?php
		$time = strtotime($_post->getData('publish_time'));
		$img = $_helper->init($_post->getImage())->resize(580,319);
	?>
	<?php if($i==0 || $i%$_row==0): ?>
	<div class="blog-slider-item">
	<?php endif;?>
	<div class="em-blog-item em-effect-13 em-wrapper-ads-12">
		<div class="em-blog-content bkg-top col-sm-12 col-xs-10">
			<?php if($img): ?>
			<a href="<?php echo $_post->getPostUrl() ?>">
				<img class="img-responsive" src="<?php echo $img ?>" alt="<?php echo $_post->getTitle() ?>">
			</a>
			<?php endif ?>
			<div class="em-blog-time">
				<p class="em-blog-date"><?php echo date('d',$time)?></p>
				<p class="em-blog-month"><?php echo date('M',$time)?></p>
			</div>
		</div>
		<div class="em-box bkg-bottom col-sm-12 col-xs-14">
			<h4 class="em-blog-title">
			      <a href="<?php echo $_post->getPostUrl() ?>"><?php echo $block->short($_post->getTitle(),35) ?>
		      </a></h4>
			<p class="em-blog-des">
				<?php echo $block->short($_post->getShortDescription(),200) ?>
			</p>
			<p><a class="link-more" href="<?php echo $_post->getPostUrl() ?>"><?php echo __('Read more') ?></a></p>
		</div>
	</div>		

	<?php if($i== $_postCollection->count() || ($i+1)%$_row==0): ?>
	</div>
	<?php endif;?>
	<?php $i++; ?>
	<?php } ?>
</div>
</div>
</div>
</div>
</div>
</div>
<script type="text/javascript">
require([
        'jquery',
        'emslider',
        'domReady!'        
        ],function($){
                if($('#<?php echo $classid ?>').length){
                  $('#<?php echo $classid ?>').addClass('owl-carousel');
                        $('#<?php echo $classid ?>').owlCarousel({
                                loop: false,
                                lazyLoad: true,
                                items: 1,
                                dots: false,
                                nav: true,
								rtl: (EM.SETTING.RTL == "1")?true:false,
                        });        
                }
        });
</script>

<?php } ?>
