<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>

<?php
	$_limit = $this->getData('limit')?$this->getData('limit'):3;
	$_postCollection = $block->getPostCollection()->setPageSize($_limit);
	//$_postCollection->getSelect()->setPageSize(4,1);
	$_helper = $this->helper('Magefan\Blog\Helper\Image');
	$_width = 580;
	$_height = 319;
	$classid = md5(json_encode($block->getPostCollection()));
	$_row = 2;
?>
<?php if ($_postCollection->count()) { ?>

<div class="em-recent-07" id="<?php echo $classid ?>">
	<?php $i=0;foreach ($_postCollection as $_post) { ?>
	<?php
		$time = strtotime($_post->getData('publish_time'));
	?>
    <?php //print_r($_post->getData()); ?>
	<div class="em-container-ads row">
		<div class="box-date">
            <span class="em-blog-date"><?php echo date('j',$time)?></span>
            <span class="em-blog-month"><?php echo date('M',$time)?></span>
        </div>
		<div class="em-detail">
			<h5 class="em-blog-title">
			      <a href="<?php echo $_post->getPostUrl() ?>"><?php echo $block->short($_post->getTitle(),30) ?>
		      </a>
			</h5>
		</div>
	</div>
	<?php $i++; ?>
	<?php } ?>
</div>
<?php } ?>
