<?php
	$helper = $this->helper('Emthemes\Slideshow\Helper\Data');
?>
<?php if($helper->checkEnabel()) : ?>
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $helper->getAssetUrl("Emthemes_Slideshow::css/style/masterslider.css")?>">
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $helper->getAssetUrl("Emthemes_Slideshow::css/skins/default/style.css")?>">
<?php else: ?>
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $helper->getAssetUrl("Emthemes_Slideshow::css/style/masterslider.css")?>">
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $helper->getAssetUrl("Emthemes_Slideshow::css/skins/default/style.css")?>">	
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $helper->getAssetUrl("Emthemes_Slideshow::css/skins/light-2/style.css")?>">
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $helper->getAssetUrl("Emthemes_Slideshow::css/skins/light-3/style.css")?>">	
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $helper->getAssetUrl("Emthemes_Slideshow::css/skins/light-4/style.css")?>">
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $helper->getAssetUrl("Emthemes_Slideshow::css/skins/light-5/style.css")?>">	
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $helper->getAssetUrl("Emthemes_Slideshow::css/skins/light-6/style.css")?>">
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $helper->getAssetUrl("Emthemes_Slideshow::css/skins/black-1/style.css")?>">	
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $helper->getAssetUrl("Emthemes_Slideshow::css/skins/black-2/style.css")?>">	
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $helper->getAssetUrl("Emthemes_Slideshow::css/skins/contrast/style.css")?>">	
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $helper->getAssetUrl("Emthemes_Slideshow::css/skins/metro/style.css")?>">
<?php endif; ?>